services:
    #Activities tab only for users
    EzPlatform\ActivitiesLog\Tab\LocationView\ActivitiesLogTab:
        parent: Ibexa\Contracts\AdminUi\Tab\AbstractTab
        tags:
            - { name: 'ibexa.admin_ui.tab', group: 'location-view' }